language: python

python:
  #- "2.7"
  #- "3.5"
  - "3.6"

install:

  - pip install numpy
  - python setup.py -q install

  #testing dependencies:
  - pip install codecov pytest-cov

script:
  - pytest tests --cov=ci_dummy


after_success:
  - codecov