language: python

python:
  #- "2.7"
  #- "3.5"
  - "3.6"

install:

  - pip install -r requirements.txt
  - python setup.py install

  #testing dependencies:
  - pip install codecov pytest-cov

script:
  - pytest --cov=ci_dummy


after_success:
  - codecov