language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install numpy python-coveralls --use-mirrors
  - python setup.py -q install

script:
  - pytest --doctest-modules --pep8 coveralls -v --cov ci_dummy --cov-report term-missing


after_success:
  - coveralls